#!/usr/bin/env sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
WORKSPACE_DIR=$(CDPATH= cd -- "${SCRIPT_DIR}/.." && pwd)
ENV_FILE="${SCRIPT_DIR}/devcontainer.env"
PROFILE_FILE="/etc/profile.d/devcontainer-env.sh"

usage() {
	cat <<'EOF'
Usage: .devcontainer/devcontainer.sh [all|machine|workspace|attach]

all        Install machine packages, persist devcontainer env, and run npm install.
machine    Install machine packages and persist devcontainer env only.
workspace  Run workspace setup only.
attach     Run the post-attach step (npm update).
EOF
}

log() {
	printf '%s\n' "$*"
}

command_exists() {
	command -v "$1" >/dev/null 2>&1
}

run_as_root() {
	if [ "$(id -u)" -eq 0 ]; then
		"$@"
		return
	fi

	if command_exists sudo; then
		sudo "$@"
		return
	fi

	log "error: root privileges are required for: $*"
	exit 1
}

shell_quote() {
	printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\''/g")"
}

load_devcontainer_env() {
	if [ -f "$ENV_FILE" ]; then
		set -a
		# shellcheck disable=SC1091
		. "$ENV_FILE"
		set +a
	fi

	: "${NODE_OPTIONS:=--max-old-space-size=4096}"
	export NODE_OPTIONS
}

write_profile_env() {
	load_devcontainer_env
	temp_file=$(mktemp)
	trap 'rm -f "$temp_file"' EXIT INT TERM HUP

	{
		printf '# Generated by %s\n' "$0"
		if [ -f "$ENV_FILE" ]; then
			while IFS= read -r line || [ -n "$line" ]; do
				case "$line" in
					''|'#'*)
						continue
						;;
				esac

				key=${line%%=*}
				value=${line#*=}
				printf 'export %s=%s\n' "$key" "$(shell_quote "$value")"
			done < "$ENV_FILE"
		fi
		printf 'export NODE_OPTIONS=%s\n' "$(shell_quote "$NODE_OPTIONS")"
	} > "$temp_file"

	run_as_root install -m 0644 "$temp_file" "$PROFILE_FILE"
	rm -f "$temp_file"
	trap - EXIT INT TERM HUP
}

detect_os() {
	if [ ! -r /etc/os-release ]; then
		log 'error: /etc/os-release is missing'
		exit 1
	fi

	OS_ID=$(awk -F= '/^ID=/{gsub(/"/, "", $2); print $2}' /etc/os-release)
	OS_CODENAME=$(awk -F= '/^VERSION_CODENAME=/{gsub(/"/, "", $2); print $2}' /etc/os-release)

	if [ -z "$OS_CODENAME" ]; then
		OS_CODENAME=$(awk -F= '/^UBUNTU_CODENAME=/{gsub(/"/, "", $2); print $2}' /etc/os-release)
	fi

	if [ -z "$OS_ID" ] || [ -z "$OS_CODENAME" ]; then
		log 'error: unsupported Linux distribution for tailscale install'
		exit 1
	fi
}

apt_install() {
	packages=$*
	run_as_root env DEBIAN_FRONTEND=noninteractive apt-get update
	run_as_root env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends $packages
}

ensure_base_packages() {
	if ! command_exists apt-get; then
		log 'error: this script currently supports Debian/Ubuntu-based containers only'
		exit 1
	fi

	apt_install ca-certificates curl git gnupg zsh
}

ensure_gh() {
	if command_exists gh; then
		return
	fi

	detect_os
	case "$OS_ID" in
		debian|ubuntu)
			;;
		*)
			log "error: unsupported Linux distribution: $OS_ID"
			exit 1
			;;
	esac

	run_as_root mkdir -p /etc/apt/keyrings
	curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | run_as_root tee /etc/apt/keyrings/githubcli-archive-keyring.gpg >/dev/null
	run_as_root chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
	printf 'deb [arch=%s signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\n' "$(dpkg --print-architecture)" | run_as_root tee /etc/apt/sources.list.d/github-cli.list >/dev/null
	apt_install gh
}

ensure_tailscale() {
	if command_exists tailscale; then
		return
	fi

	detect_os
	case "$OS_ID" in
		debian|ubuntu)
			;;
		*)
			log "error: unsupported Linux distribution: $OS_ID"
			exit 1
			;;
	esac

	run_as_root mkdir -p /usr/share/keyrings
	curl -fsSL "https://pkgs.tailscale.com/stable/${OS_ID}/${OS_CODENAME}.noarmor.gpg" | run_as_root tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
	curl -fsSL "https://pkgs.tailscale.com/stable/${OS_ID}/${OS_CODENAME}.tailscale-keyring.list" | run_as_root tee /etc/apt/sources.list.d/tailscale.list >/dev/null
	apt_install tailscale
}

setup_machine() {
	ensure_base_packages
	ensure_gh
	ensure_tailscale
	write_profile_env
}

setup_workspace() {
	load_devcontainer_env
	cd "$WORKSPACE_DIR"

	if [ -f package.json ]; then
		npm install
	fi
}

post_attach() {
	load_devcontainer_env
	cd "$WORKSPACE_DIR"

	if [ -f package.json ]; then
		npm update
	fi
}

main() {
	mode=${1:-all}

	case "$mode" in
		all)
			setup_machine
			setup_workspace
			;;
		machine)
			setup_machine
			;;
		workspace)
			setup_workspace
			;;
		attach)
			post_attach
			;;
		-h|--help|help)
			usage
			;;
		*)
			usage >&2
			exit 1
			;;
	esac
}

main "$@"
